<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\SYS_colaboradores;

class colaboradoresSeeder extends Seeder
{
    public function run()
    {
        $colaboradores = [
            ['identificador' => '211532440', 'nombre1' => 'Isabel', 'nombre2' => 'Margarita', 'apellido1' => 'García', 'apellido2' => 'Abalos' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'IsabelGarcia@gmail.com', 'correoEmpresa' => 'igarcia@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532441', 'nombre1' => 'Isabel', 'nombre2' => 'Margarita', 'apellido1' => 'González', 'apellido2' => 'Sanzo' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'IsabelGonzalez@gmail.com', 'correoEmpresa' => 'iGonzalez@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532443', 'nombre1' => 'Catherine', 'nombre2' => 'TEMPORAL', 'apellido1' => 'Cifuentes', 'apellido2' => 'Araneda' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'CatherineCifuentes@gmail.com', 'correoEmpresa' => 'ccifuentes@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532445', 'nombre1' => 'Guillermo', 'nombre2' => 'TEMPORAL', 'apellido1' => 'Acosta', 'apellido2' => 'León' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '2', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'GuillermoAcosta@gmail.com', 'correoEmpresa' => 'gacosta@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532446', 'nombre1' => 'Eduardo', 'nombre2' => 'TEMPORAL', 'apellido1' => 'Mizon', 'apellido2' => 'Costa' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'EduardoMizon@gmail.com', 'correoEmpresa' => 'emizon@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532447', 'nombre1' => 'Flavio', 'nombre2' => 'TEMPORAL', 'apellido1' => 'Dib', 'apellido2' => 'Maluk' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'FlavioDib@gmail.com', 'correoEmpresa' => 'fdib@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532442', 'nombre1' => 'María', 'nombre2' => 'Inés', 'apellido1' => 'Morales', 'apellido2' => 'Barraza' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'MaríaInés@gmail.com', 'correoEmpresa' => 'mines@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532444', 'nombre1' => 'Valentina', 'nombre2' => 'Del Pilar', 'apellido1' => 'Cornejo', 'apellido2' => 'Altamirano' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'ValentinaCornejo@gmail.com', 'correoEmpresa' => 'vcornejo@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532448', 'nombre1' => 'Benjamin', 'nombre2' => 'TEMPORAL', 'apellido1' => 'Dib', 'apellido2' => 'Puelma' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'BenjaminDib@gmail.com', 'correoEmpresa' => 'bdib@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532449', 'nombre1' => 'Patricio', 'nombre2' => 'TEMPORAL', 'apellido1' => 'Bocaz', 'apellido2' => 'Ahumada' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'PatricioBocaz@gmail.com', 'correoEmpresa' => 'pbocaz@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532450', 'nombre1' => 'Super-Administrador', 'nombre2' => 'TEMPORAL', 'apellido1' => 'TEMPORAL', 'apellido2' => 'TEMPORAL' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'super.administrador@gmail.com', 'correoEmpresa' => 'superadministrador@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532451', 'nombre1' => 'Bastián', 'nombre2' => 'TEMPORAL', 'apellido1' => 'Contreras', 'apellido2' => 'Wasilkowski' , 'idNacionalidad' => '1', 'fechaNac' => '15/09/2000', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'BastianContreras@gmail.com', 'correoEmpresa' => 'bcontreras@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            ['identificador' => '211532452', 'nombre1' => 'Sebastián', 'nombre2' => 'TEMPORAL', 'apellido1' => 'Jerez', 'apellido2' => 'Vega' , 'idNacionalidad' => '1', 'fechaNac' => '24/10/2002', 'idPais' => '1', 'idRegion' => '1', 'idComuna' => '1', 'sector' => 'Forestal', 'direccion' => 'Camino cintura 2717', 'correoPersonal' => 'SebastianJerez@gmail.com', 'correoEmpresa' => 'sjerez@amphora.cl', 'telefonoEmpresa' => '+5693232314', 'telefonoPersonal' => '+56931415526', 'idEstadoCivil' => '2', 'idDepartamento' => '1', 'idArea' => '1', 'cargo' => 'Jefe de Área', 'idSistemaSalud' => '4', 'idAfpAsociada' => '4'],
            
        ];

        foreach($colaboradores as $colaborador){
            $colaborador1 = SYS_colaboradores::create($colaborador);
        };

    }
}