<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\SYS_comunas;

class comunasSeeder extends Seeder
{
    public function run()
    {
        $comunas = [
            ['comuna' => 'Arica', 'idRegion' => '1', 'idRegionComuna' => '1Arica'],
            ['comuna' => 'Camarones', 'idRegion' => '1', 'idRegionComuna' => '1Camarones'],
            ['comuna' => 'General Lagos', 'idRegion' => '1', 'idRegionComuna' => '1General Lagos'],
            ['comuna' => 'Putre', 'idRegion' => '1', 'idRegionComuna' => '1Putre'],
            ['comuna' => 'Alto Hospicio', 'idRegion' => '2', 'idRegionComuna' => '2Alto Hospicio'],
            ['comuna' => 'Iquique', 'idRegion' => '2', 'idRegionComuna' => '2Iquique'],
            ['comuna' => 'Camiña', 'idRegion' => '2', 'idRegionComuna' => '2Camiña'],
            ['comuna' => 'Colchane', 'idRegion' => '2', 'idRegionComuna' => '2Colchane'],
            ['comuna' => 'Huara', 'idRegion' => '2', 'idRegionComuna' => '2Huara'],
            ['comuna' => 'Pica', 'idRegion' => '2', 'idRegionComuna' => '2Pica'],
            ['comuna' => 'Pozo Almonte', 'idRegion' => '2', 'idRegionComuna' => '2Pozo Almonte'],
            ['comuna' => 'Tocopilla', 'idRegion' => '3', 'idRegionComuna' => '3Tocopilla'],
            ['comuna' => 'María Elena', 'idRegion' => '3', 'idRegionComuna' => '3María Elena'],
            ['comuna' => 'Calama', 'idRegion' => '3', 'idRegionComuna' => '3Calama'],
            ['comuna' => 'Ollague', 'idRegion' => '3', 'idRegionComuna' => '3Ollague'],
            ['comuna' => 'San Pedro de Atacama', 'idRegion' => '3', 'idRegionComuna' => '3San Pedro de Atacama'],
            ['comuna' => 'Antofagasta', 'idRegion' => '3', 'idRegionComuna' => '3Antofagasta'],
            ['comuna' => 'Mejillones', 'idRegion' => '3', 'idRegionComuna' => '3Mejillones'],
            ['comuna' => 'Sierra Gorda', 'idRegion' => '3', 'idRegionComuna' => '3Sierra Gorda'],
            ['comuna' => 'Taltal', 'idRegion' => '3', 'idRegionComuna' => '3Taltal'],
            ['comuna' => 'Chañaral', 'idRegion' => '4', 'idRegionComuna' => '4Chañaral'],
            ['comuna' => 'Diego de Almagro', 'idRegion' => '4', 'idRegionComuna' => '4Diego de Almagro'],
            ['comuna' => 'Copiapó', 'idRegion' => '4', 'idRegionComuna' => '4Copiapó'],
            ['comuna' => 'Caldera', 'idRegion' => '4', 'idRegionComuna' => '4Caldera'],
            ['comuna' => 'Tierra Amarilla', 'idRegion' => '4', 'idRegionComuna' => '4Tierra Amarilla'],
            ['comuna' => 'Vallenar', 'idRegion' => '4', 'idRegionComuna' => '4Vallenar'],
            ['comuna' => 'Alto del Carmen', 'idRegion' => '4', 'idRegionComuna' => '4Alto del Carmen'],
            ['comuna' => 'Freirina', 'idRegion' => '4', 'idRegionComuna' => '4Freirina'],
            ['comuna' => 'Huasco', 'idRegion' => '4', 'idRegionComuna' => '4Huasco'],
            ['comuna' => 'La Serena', 'idRegion' => '5', 'idRegionComuna' => '5La Serena'],
            ['comuna' => 'Coquimbo', 'idRegion' => '5', 'idRegionComuna' => '5Coquimbo'],
            ['comuna' => 'Andacollo', 'idRegion' => '5', 'idRegionComuna' => '5Andacollo'],
            ['comuna' => 'La Higuera', 'idRegion' => '5', 'idRegionComuna' => '5La Higuera'],
            ['comuna' => 'Paihuano', 'idRegion' => '5', 'idRegionComuna' => '5Paihuano'],
            ['comuna' => 'Vicuña', 'idRegion' => '5', 'idRegionComuna' => '5Vicuña'],
            ['comuna' => 'Ovalle', 'idRegion' => '5', 'idRegionComuna' => '5Ovalle'],
            ['comuna' => 'Combarbalá', 'idRegion' => '5', 'idRegionComuna' => '5Combarbalá'],
            ['comuna' => 'Monte Patria', 'idRegion' => '5', 'idRegionComuna' => '5Monte Patria'],
            ['comuna' => 'Punitaqui', 'idRegion' => '5', 'idRegionComuna' => '5Punitaqui'],
            ['comuna' => 'Río Hurtado', 'idRegion' => '5', 'idRegionComuna' => '5Río Hurtado'],
            ['comuna' => 'Illapel', 'idRegion' => '5', 'idRegionComuna' => '5Illapel'],
            ['comuna' => 'Canela', 'idRegion' => '5', 'idRegionComuna' => '5Canela'],
            ['comuna' => 'Los Vilos', 'idRegion' => '5', 'idRegionComuna' => '5Los Vilos'],
            ['comuna' => 'Salamanca', 'idRegion' => '5', 'idRegionComuna' => '5Salamanca'],
            ['comuna' => 'La Ligua', 'idRegion' => '6', 'idRegionComuna' => '6La Ligua'],
            ['comuna' => 'Cabildo', 'idRegion' => '6', 'idRegionComuna' => '6Cabildo'],
            ['comuna' => 'Zapallar', 'idRegion' => '6', 'idRegionComuna' => '6Zapallar'],
            ['comuna' => 'Papudo', 'idRegion' => '6', 'idRegionComuna' => '6Papudo'],
            ['comuna' => 'Petorca', 'idRegion' => '6', 'idRegionComuna' => '6Petorca'],
            ['comuna' => 'Los Andes', 'idRegion' => '6', 'idRegionComuna' => '6Los Andes'],
            ['comuna' => 'San Esteban', 'idRegion' => '6', 'idRegionComuna' => '6San Esteban'],
            ['comuna' => 'Calle Larga', 'idRegion' => '6', 'idRegionComuna' => '6Calle Larga'],
            ['comuna' => 'Rinconada', 'idRegion' => '6', 'idRegionComuna' => '6Rinconada'],
            ['comuna' => 'San Felipe', 'idRegion' => '6', 'idRegionComuna' => '6San Felipe'],
            ['comuna' => 'Llaillay', 'idRegion' => '6', 'idRegionComuna' => '6Llaillay'],
            ['comuna' => 'Putaendo', 'idRegion' => '6', 'idRegionComuna' => '6Putaendo'],
            ['comuna' => 'Santa María', 'idRegion' => '6', 'idRegionComuna' => '6Santa María'],
            ['comuna' => 'Catemu', 'idRegion' => '6', 'idRegionComuna' => '6Catemu'],
            ['comuna' => 'Panquehue', 'idRegion' => '6', 'idRegionComuna' => '6Panquehue'],
            ['comuna' => 'Quillota', 'idRegion' => '6', 'idRegionComuna' => '6Quillota'],
            ['comuna' => 'La Cruz', 'idRegion' => '6', 'idRegionComuna' => '6La Cruz'],
            ['comuna' => 'La Calera', 'idRegion' => '6', 'idRegionComuna' => '6La Calera'],
            ['comuna' => 'Nogales', 'idRegion' => '6', 'idRegionComuna' => '6Nogales'],
            ['comuna' => 'Hijuelas', 'idRegion' => '6', 'idRegionComuna' => '6Hijuelas'],
            ['comuna' => 'Valparaíso', 'idRegion' => '6', 'idRegionComuna' => '6Valparaíso'],
            ['comuna' => 'Viña del Mar', 'idRegion' => '6', 'idRegionComuna' => '6Viña del Mar'],
            ['comuna' => 'Concón', 'idRegion' => '6', 'idRegionComuna' => '6Concón'],
            ['comuna' => 'Quintero', 'idRegion' => '6', 'idRegionComuna' => '6Quintero'],
            ['comuna' => 'Puchuncaví', 'idRegion' => '6', 'idRegionComuna' => '6Puchuncaví'],
            ['comuna' => 'Casablanca', 'idRegion' => '6', 'idRegionComuna' => '6Casablanca'],
            ['comuna' => 'Juan Fernández', 'idRegion' => '6', 'idRegionComuna' => '6Juan Fernández'],
            ['comuna' => 'San Antonio', 'idRegion' => '6', 'idRegionComuna' => '6San Antonio'],
            ['comuna' => 'Cartagena', 'idRegion' => '6', 'idRegionComuna' => '6Cartagena'],
            ['comuna' => 'El Tabo', 'idRegion' => '6', 'idRegionComuna' => '6El Tabo'],
            ['comuna' => 'El Quisco', 'idRegion' => '6', 'idRegionComuna' => '6El Quisco'],
            ['comuna' => 'Algarrobo', 'idRegion' => '6', 'idRegionComuna' => '6Algarrobo'],
            ['comuna' => 'Santo Domingo', 'idRegion' => '6', 'idRegionComuna' => '6Santo Domingo'],
            ['comuna' => 'Isla de Pascua', 'idRegion' => '6', 'idRegionComuna' => '6Isla de Pascua'],
            ['comuna' => 'Quilpué', 'idRegion' => '6', 'idRegionComuna' => '6Quilpué'],
            ['comuna' => 'Limache', 'idRegion' => '6', 'idRegionComuna' => '6Limache'],
            ['comuna' => 'Olmué', 'idRegion' => '6', 'idRegionComuna' => '6Olmué'],
            ['comuna' => 'Villa Alemana', 'idRegion' => '6', 'idRegionComuna' => '6Villa Alemana'],
            ['comuna' => 'Colina', 'idRegion' => '7', 'idRegionComuna' => '7Colina'],
            ['comuna' => 'Lampa', 'idRegion' => '7', 'idRegionComuna' => '7Lampa'],
            ['comuna' => 'Tiltil', 'idRegion' => '7', 'idRegionComuna' => '7Tiltil'],
            ['comuna' => 'Santiago', 'idRegion' => '7', 'idRegionComuna' => '7Santiago'],
            ['comuna' => 'Vitacura', 'idRegion' => '7', 'idRegionComuna' => '7Vitacura'],
            ['comuna' => 'San Ramón', 'idRegion' => '7', 'idRegionComuna' => '7San Ramón'],
            ['comuna' => 'San Miguel', 'idRegion' => '7', 'idRegionComuna' => '7San Miguel'],
            ['comuna' => 'San Joaquín', 'idRegion' => '7', 'idRegionComuna' => '7San Joaquín'],
            ['comuna' => 'Renca', 'idRegion' => '7', 'idRegionComuna' => '7Renca'],
            ['comuna' => 'Recoleta', 'idRegion' => '7', 'idRegionComuna' => '7Recoleta'],
            ['comuna' => 'Quinta Normal', 'idRegion' => '7', 'idRegionComuna' => '7Quinta Normal'],
            ['comuna' => 'Quilicura', 'idRegion' => '7', 'idRegionComuna' => '7Quilicura'],
            ['comuna' => 'Pudahuel', 'idRegion' => '7', 'idRegionComuna' => '7Pudahuel'],
            ['comuna' => 'Providencia', 'idRegion' => '7', 'idRegionComuna' => '7Providencia'],
            ['comuna' => 'Peñalolén', 'idRegion' => '7', 'idRegionComuna' => '7Peñalolén'],
            ['comuna' => 'Pedro Aguirre Cerda', 'idRegion' => '7', 'idRegionComuna' => '7Pedro Aguirre Cerda'],
            ['comuna' => 'Ñuñoa', 'idRegion' => '7', 'idRegionComuna' => '7Ñuñoa'],
            ['comuna' => 'Maipú', 'idRegion' => '7', 'idRegionComuna' => '7Maipú'],
            ['comuna' => 'Macul', 'idRegion' => '7', 'idRegionComuna' => '7Macul'],
            ['comuna' => 'Lo Prado', 'idRegion' => '7', 'idRegionComuna' => '7Lo Prado'],
            ['comuna' => 'Lo Espejo', 'idRegion' => '7', 'idRegionComuna' => '7Lo Espejo'],
            ['comuna' => 'Lo Barnechea', 'idRegion' => '7', 'idRegionComuna' => '7Lo Barnechea'],
            ['comuna' => 'Las Condes', 'idRegion' => '7', 'idRegionComuna' => '7Las Condes'],
            ['comuna' => 'La Reina', 'idRegion' => '7', 'idRegionComuna' => '7La Reina'],
            ['comuna' => 'La Pintana', 'idRegion' => '7', 'idRegionComuna' => '7La Pintana'],
            ['comuna' => 'La Granja', 'idRegion' => '7', 'idRegionComuna' => '7La Granja'],
            ['comuna' => 'La Florida', 'idRegion' => '7', 'idRegionComuna' => '7La Florida'],
            ['comuna' => 'La Cisterna', 'idRegion' => '7', 'idRegionComuna' => '7La Cisterna'],
            ['comuna' => 'Independencia', 'idRegion' => '7', 'idRegionComuna' => '7Independencia'],
            ['comuna' => 'Huechuraba', 'idRegion' => '7', 'idRegionComuna' => '7Huechuraba'],
            ['comuna' => 'Estación Central', 'idRegion' => '7', 'idRegionComuna' => '7Estación Central'],
            ['comuna' => 'El Bosque', 'idRegion' => '7', 'idRegionComuna' => '7El Bosque'],
            ['comuna' => 'Conchalí', 'idRegion' => '7', 'idRegionComuna' => '7Conchalí'],
            ['comuna' => 'Cerro Navia', 'idRegion' => '7', 'idRegionComuna' => '7Cerro Navia'],
            ['comuna' => 'Cerrillos', 'idRegion' => '7', 'idRegionComuna' => '7Cerrillos'],
            ['comuna' => 'Puente Alto', 'idRegion' => '7', 'idRegionComuna' => '7Puente Alto'],
            ['comuna' => 'San José de Maipo', 'idRegion' => '7', 'idRegionComuna' => '7San José de Maipo'],
            ['comuna' => 'Pirque', 'idRegion' => '7', 'idRegionComuna' => '7Pirque'],
            ['comuna' => 'San Bernardo', 'idRegion' => '7', 'idRegionComuna' => '7San Bernardo'],
            ['comuna' => 'Buin', 'idRegion' => '7', 'idRegionComuna' => '7Buin'],
            ['comuna' => 'Paine', 'idRegion' => '7', 'idRegionComuna' => '7Paine'],
            ['comuna' => 'Calera de Tango', 'idRegion' => '7', 'idRegionComuna' => '7Calera de Tango'],
            ['comuna' => 'Melipilla', 'idRegion' => '7', 'idRegionComuna' => '7Melipilla'],
            ['comuna' => 'Alhué', 'idRegion' => '7', 'idRegionComuna' => '7Alhué'],
            ['comuna' => 'Curacaví', 'idRegion' => '7', 'idRegionComuna' => '7Curacaví'],
            ['comuna' => 'María Pinto', 'idRegion' => '7', 'idRegionComuna' => '7María Pinto'],
            ['comuna' => 'San Pedro', 'idRegion' => '7', 'idRegionComuna' => '7San Pedro'],
            ['comuna' => 'Isla de Maipo', 'idRegion' => '7', 'idRegionComuna' => '7Isla de Maipo'],
            ['comuna' => 'El Monte', 'idRegion' => '7', 'idRegionComuna' => '7El'],
            ['comuna' => 'Padre Hurtado', 'idRegion' => '7', 'idRegionComuna' => '7Padre Hurtado'],
            ['comuna' => 'Peñaflor', 'idRegion' => '7', 'idRegionComuna' => '7Peñaflor'],
            ['comuna' => 'Talagante', 'idRegion' => '7', 'idRegionComuna' => '7Talagante'],
            ['comuna' => 'Codegua', 'idRegion' => '8', 'idRegionComuna' => '8Codegua'],
            ['comuna' => 'Coínco', 'idRegion' => '8', 'idRegionComuna' => '8Coínco'],
            ['comuna' => 'Coltauco', 'idRegion' => '8', 'idRegionComuna' => '8Coltauco'],
            ['comuna' => 'Doñihue', 'idRegion' => '8', 'idRegionComuna' => '8Doñihue'],
            ['comuna' => 'Graneros', 'idRegion' => '8', 'idRegionComuna' => '8Graneros'],
            ['comuna' => 'Las Cabras', 'idRegion' => '8', 'idRegionComuna' => '8Las Cabras'],
            ['comuna' => 'Machalí', 'idRegion' => '8', 'idRegionComuna' => '8Machalí'],
            ['comuna' => 'Malloa', 'idRegion' => '8', 'idRegionComuna' => '8Malloa'],
            ['comuna' => 'Mostazal', 'idRegion' => '8', 'idRegionComuna' => '8Mostazal'],
            ['comuna' => 'Olivar', 'idRegion' => '8', 'idRegionComuna' => '8Olivar'],
            ['comuna' => 'Peumo', 'idRegion' => '8', 'idRegionComuna' => '8Peumo'],
            ['comuna' => 'Pichidegua', 'idRegion' => '8', 'idRegionComuna' => '8Pichidegua'],
            ['comuna' => 'Quinta de Tilcoco', 'idRegion' => '8', 'idRegionComuna' => '8Quinta de Tilcoco'],
            ['comuna' => 'Rancagua', 'idRegion' => '8', 'idRegionComuna' => '8Rancagua'],
            ['comuna' => 'Rengo', 'idRegion' => '8', 'idRegionComuna' => '8Rengo'],
            ['comuna' => 'Requínoa', 'idRegion' => '8', 'idRegionComuna' => '8Requínoa'],
            ['comuna' => 'San Vicente de Tagua Tagua', 'idRegion' => '8', 'idRegionComuna' => '8San Vicente de Tagua Tagua'],
            ['comuna' => 'Chépica', 'idRegion' => '8', 'idRegionComuna' => '8Chépica'],
            ['comuna' => 'Chimbarongo', 'idRegion' => '8', 'idRegionComuna' => '8Chimbarongo'],
            ['comuna' => 'Lolol', 'idRegion' => '8', 'idRegionComuna' => '8Lolol'],
            ['comuna' => 'Nancagua', 'idRegion' => '8', 'idRegionComuna' => '8Nancagua'],
            ['comuna' => 'Palmilla', 'idRegion' => '8', 'idRegionComuna' => '8Palmilla'],
            ['comuna' => 'Peralillo', 'idRegion' => '8', 'idRegionComuna' => '8Peralillo'],
            ['comuna' => 'Placilla', 'idRegion' => '8', 'idRegionComuna' => '8Placilla'],
            ['comuna' => 'Pumanque', 'idRegion' => '8', 'idRegionComuna' => '8Pumanque'],
            ['comuna' => 'San Fernando', 'idRegion' => '8', 'idRegionComuna' => '8San Fernando'],
            ['comuna' => 'Santa Cruz', 'idRegion' => '8', 'idRegionComuna' => '8Santa Cruz'],
            ['comuna' => 'La Estrella', 'idRegion' => '8', 'idRegionComuna' => '8La Estrella'],
            ['comuna' => 'Litueche', 'idRegion' => '8', 'idRegionComuna' => '8Litueche'],
            ['comuna' => 'Marchigüe', 'idRegion' => '8', 'idRegionComuna' => '8Marchigüe'],
            ['comuna' => 'Navidad', 'idRegion' => '8', 'idRegionComuna' => '8Navidad'],
            ['comuna' => 'Paredones', 'idRegion' => '8', 'idRegionComuna' => '8Paredones'],
            ['comuna' => 'Pichilemu', 'idRegion' => '8', 'idRegionComuna' => '8Pichilemu'],
            ['comuna' => 'Curicó', 'idRegion' => '9', 'idRegionComuna' => '9Curicó'],
            ['comuna' => 'Hualañé', 'idRegion' => '9', 'idRegionComuna' => '9Hualañé'],
            ['comuna' => 'Licantén', 'idRegion' => '9', 'idRegionComuna' => '9Licantén'],
            ['comuna' => 'Molina', 'idRegion' => '9', 'idRegionComuna' => '9Molina'],
            ['comuna' => 'Rauco', 'idRegion' => '9', 'idRegionComuna' => '9Rauco'],
            ['comuna' => 'Romeral', 'idRegion' => '9', 'idRegionComuna' => '9Romeral'],
            ['comuna' => 'Sagrada Familia', 'idRegion' => '9', 'idRegionComuna' => '9Sagrada Familia'],
            ['comuna' => 'Teno', 'idRegion' => '9', 'idRegionComuna' => '9Teno'],
            ['comuna' => 'Vichuquén', 'idRegion' => '9', 'idRegionComuna' => '9Vichuquén'],
            ['comuna' => 'Talca', 'idRegion' => '9', 'idRegionComuna' => '9Talca'],
            ['comuna' => 'San Clemente', 'idRegion' => '9', 'idRegionComuna' => '9San Clemente'],
            ['comuna' => 'Pelarco', 'idRegion' => '9', 'idRegionComuna' => '9Pelarco'],
            ['comuna' => 'Pencahue', 'idRegion' => '9', 'idRegionComuna' => '9Pencahue'],
            ['comuna' => 'Maule', 'idRegion' => '9', 'idRegionComuna' => '9Maule'],
            ['comuna' => 'San Rafael', 'idRegion' => '9', 'idRegionComuna' => '9San Rafael'],
            ['comuna' => 'Curepto', 'idRegion' => '9', 'idRegionComuna' => '9Curepto'],
            ['comuna' => 'Constitución', 'idRegion' => '9', 'idRegionComuna' => '9Constitución'],
            ['comuna' => 'Empedrado', 'idRegion' => '9', 'idRegionComuna' => '9Empedrado'],
            ['comuna' => 'Río Claro', 'idRegion' => '9', 'idRegionComuna' => '9Río Claro'],
            ['comuna' => 'Linares', 'idRegion' => '9', 'idRegionComuna' => '9Linares'],
            ['comuna' => 'San Javier', 'idRegion' => '9', 'idRegionComuna' => '9San Javier'],
            ['comuna' => 'Parral', 'idRegion' => '9', 'idRegionComuna' => '9Parral'],
            ['comuna' => 'Villa Alegre', 'idRegion' => '9', 'idRegionComuna' => '9Villa Alegre'],
            ['comuna' => 'Longaví', 'idRegion' => '9', 'idRegionComuna' => '9Longaví'],
            ['comuna' => 'Colbún', 'idRegion' => '9', 'idRegionComuna' => '9Colbún'],
            ['comuna' => 'Retiro', 'idRegion' => '9', 'idRegionComuna' => '9Retiro'],
            ['comuna' => 'Yerbas Buenas', 'idRegion' => '9', 'idRegionComuna' => '9Yerbas Buenas'],
            ['comuna' => 'Cauquenes', 'idRegion' => '9', 'idRegionComuna' => '9Cauquenes'],
            ['comuna' => 'Chanco', 'idRegion' => '9', 'idRegionComuna' => '9Chanco'],
            ['comuna' => 'Pelluhue', 'idRegion' => '9', 'idRegionComuna' => '9Pelluhue'],
            ['comuna' => 'Bulnes', 'idRegion' => '10', 'idRegionComuna' => '10Bulnes'],
            ['comuna' => 'Chillán', 'idRegion' => '10', 'idRegionComuna' => '10Chillán'],
            ['comuna' => 'Chillán Viejo', 'idRegion' => '10', 'idRegionComuna' => '10Chillán Viejo'],
            ['comuna' => 'El Carmen', 'idRegion' => '10', 'idRegionComuna' => '10El Carmen'],
            ['comuna' => 'Pemuco', 'idRegion' => '10', 'idRegionComuna' => '10Pemuco'],
            ['comuna' => 'Pinto', 'idRegion' => '10', 'idRegionComuna' => '10Pinto'],
            ['comuna' => 'Quillón', 'idRegion' => '10', 'idRegionComuna' => '10Quillón'],
            ['comuna' => 'San Ignacio', 'idRegion' => '10', 'idRegionComuna' => '10San Ignacio'],
            ['comuna' => 'Yungay', 'idRegion' => '10', 'idRegionComuna' => '10Yungay'],
            ['comuna' => 'Cobquecura', 'idRegion' => '10', 'idRegionComuna' => '10Cobquecura'],
            ['comuna' => 'Coelemu', 'idRegion' => '10', 'idRegionComuna' => '10Coelemu'],
            ['comuna' => 'Ninhue', 'idRegion' => '10', 'idRegionComuna' => '10Ninhue'],
            ['comuna' => 'Portezuelo', 'idRegion' => '10', 'idRegionComuna' => '10Portezuelo'],
            ['comuna' => 'Quirihue', 'idRegion' => '10', 'idRegionComuna' => '10Quirihue'],
            ['comuna' => 'Ránquil', 'idRegion' => '10', 'idRegionComuna' => '10Ránquil'],
            ['comuna' => 'Treguaco', 'idRegion' => '10', 'idRegionComuna' => '10Treguaco'],
            ['comuna' => 'San Carlos', 'idRegion' => '10', 'idRegionComuna' => '10San Carlos'],
            ['comuna' => 'Coihueco', 'idRegion' => '10', 'idRegionComuna' => '10Coihueco'],
            ['comuna' => 'San Nicolás', 'idRegion' => '10', 'idRegionComuna' => '10San Nicolás'],
            ['comuna' => 'Ñiquén', 'idRegion' => '10', 'idRegionComuna' => '10Ñiquén'],
            ['comuna' => 'San Fabián', 'idRegion' => '10', 'idRegionComuna' => '10San Fabián'],
            ['comuna' => 'Alto Biobío', 'idRegion' => '11', 'idRegionComuna' => '11Alto Biobío'],
            ['comuna' => 'Antuco', 'idRegion' => '11', 'idRegionComuna' => '11Antuco'],
            ['comuna' => 'Cabrero', 'idRegion' => '11', 'idRegionComuna' => '11Cabrero'],
            ['comuna' => 'Laja', 'idRegion' => '11', 'idRegionComuna' => '11Laja'],
            ['comuna' => 'Los Ángeles', 'idRegion' => '11', 'idRegionComuna' => '11Los Ángeles'],
            ['comuna' => 'Mulchén', 'idRegion' => '11', 'idRegionComuna' => '11Mulchén'],
            ['comuna' => 'Nacimiento', 'idRegion' => '11', 'idRegionComuna' => '11Nacimiento'],
            ['comuna' => 'Negrete', 'idRegion' => '11', 'idRegionComuna' => '11Negrete'],
            ['comuna' => 'Quilaco', 'idRegion' => '11', 'idRegionComuna' => '11Quilaco'],
            ['comuna' => 'Quilleco', 'idRegion' => '11', 'idRegionComuna' => '11Quilleco'],
            ['comuna' => 'San Rosendo', 'idRegion' => '11', 'idRegionComuna' => '11San Rosendo'],
            ['comuna' => 'Santa Bárbara', 'idRegion' => '11', 'idRegionComuna' => '11Santa Bárbara'],
            ['comuna' => 'Tucapel', 'idRegion' => '11', 'idRegionComuna' => '11Tucapel'],
            ['comuna' => 'Yumbel', 'idRegion' => '11', 'idRegionComuna' => '11Yumbel'],
            ['comuna' => 'Concepción', 'idRegion' => '11', 'idRegionComuna' => '11Concepción'],
            ['comuna' => 'Coronel', 'idRegion' => '11', 'idRegionComuna' => '11Coronel'],
            ['comuna' => 'Chiguayante', 'idRegion' => '11', 'idRegionComuna' => '11Chiguayante'],
            ['comuna' => 'Florida', 'idRegion' => '11', 'idRegionComuna' => '11Florida'],
            ['comuna' => 'Hualpén', 'idRegion' => '11', 'idRegionComuna' => '11Hualpén'],
            ['comuna' => 'Hualqui', 'idRegion' => '11', 'idRegionComuna' => '11Hualqui'],
            ['comuna' => 'Lota', 'idRegion' => '11', 'idRegionComuna' => '11Lota'],
            ['comuna' => 'Penco', 'idRegion' => '11', 'idRegionComuna' => '11Penco'],
            ['comuna' => 'San Pedro de La Paz', 'idRegion' => '11', 'idRegionComuna' => '11San Pedro de La Paz'],
            ['comuna' => 'Santa Juana', 'idRegion' => '11', 'idRegionComuna' => '11Santa Juana'],
            ['comuna' => 'Talcahuano', 'idRegion' => '11', 'idRegionComuna' => '11Talcahuano'],
            ['comuna' => 'Tomé', 'idRegion' => '11', 'idRegionComuna' => '11Tomé'],
            ['comuna' => 'Arauco', 'idRegion' => '11', 'idRegionComuna' => '11Arauco'],
            ['comuna' => 'Cañete', 'idRegion' => '11', 'idRegionComuna' => '11Cañete'],
            ['comuna' => 'Contulmo', 'idRegion' => '11', 'idRegionComuna' => '11Contulmo'],
            ['comuna' => 'Curanilahue', 'idRegion' => '11', 'idRegionComuna' => '11Curanilahue'],
            ['comuna' => 'Lebu', 'idRegion' => '11', 'idRegionComuna' => '11Lebu'],
            ['comuna' => 'Los Álamos', 'idRegion' => '11', 'idRegionComuna' => '11Los Álamos'],
            ['comuna' => 'Tirúa', 'idRegion' => '11', 'idRegionComuna' => '11Tirúa'],
            ['comuna' => 'Angol', 'idRegion' => '12', 'idRegionComuna' => '12Angol'],
            ['comuna' => 'Collipulli', 'idRegion' => '12', 'idRegionComuna' => '12Collipulli'],
            ['comuna' => 'Curacautín', 'idRegion' => '12', 'idRegionComuna' => '12Curacautín'],
            ['comuna' => 'Ercilla', 'idRegion' => '12', 'idRegionComuna' => '12Ercilla'],
            ['comuna' => 'Lonquimay', 'idRegion' => '12', 'idRegionComuna' => '12Lonquimay'],
            ['comuna' => 'Los Sauces', 'idRegion' => '12', 'idRegionComuna' => '12Los Sauces'],
            ['comuna' => 'Lumaco', 'idRegion' => '12', 'idRegionComuna' => '12Lumaco'],
            ['comuna' => 'Purén', 'idRegion' => '12', 'idRegionComuna' => '12Purén'],
            ['comuna' => 'Renaico', 'idRegion' => '12', 'idRegionComuna' => '12Renaico'],
            ['comuna' => 'Traiguén', 'idRegion' => '12', 'idRegionComuna' => '12Traiguén'],
            ['comuna' => 'Victoria', 'idRegion' => '12', 'idRegionComuna' => '12Victoria'],
            ['comuna' => 'Temuco', 'idRegion' => '12', 'idRegionComuna' => '12Temuco'],
            ['comuna' => 'Carahue', 'idRegion' => '12', 'idRegionComuna' => '12Carahue'],
            ['comuna' => 'Cholchol', 'idRegion' => '12', 'idRegionComuna' => '12Cholchol'],
            ['comuna' => 'Cunco', 'idRegion' => '12', 'idRegionComuna' => '12Cunco'],
            ['comuna' => 'Curarrehue', 'idRegion' => '12', 'idRegionComuna' => '12Curarrehue'],
            ['comuna' => 'Freire', 'idRegion' => '12', 'idRegionComuna' => '12Freire'],
            ['comuna' => 'Galvarino', 'idRegion' => '12', 'idRegionComuna' => '12Galvarino'],
            ['comuna' => 'Gorbea', 'idRegion' => '12', 'idRegionComuna' => '12Gorbea'],
            ['comuna' => 'Lautaro', 'idRegion' => '12', 'idRegionComuna' => '12Lautaro'],
            ['comuna' => 'Loncoche', 'idRegion' => '12', 'idRegionComuna' => '12Loncoche'],
            ['comuna' => 'Melipeuco', 'idRegion' => '12', 'idRegionComuna' => '12Melipeuco'],
            ['comuna' => 'Nueva Imperial', 'idRegion' => '12', 'idRegionComuna' => '12Nueva Imperial'],
            ['comuna' => 'Padre Las Casas', 'idRegion' => '12', 'idRegionComuna' => '12Padre Las Casas'],
            ['comuna' => 'Perquenco', 'idRegion' => '12', 'idRegionComuna' => '12Perquenco'],
            ['comuna' => 'Pitrufquén', 'idRegion' => '12', 'idRegionComuna' => '12Pitrufquén'],
            ['comuna' => 'Pucón', 'idRegion' => '12', 'idRegionComuna' => '12Pucón'],
            ['comuna' => 'Saavedra', 'idRegion' => '12', 'idRegionComuna' => '12Saavedra'],
            ['comuna' => 'Teodoro Schmidt', 'idRegion' => '12', 'idRegionComuna' => '12Teodoro Schmidt'],
            ['comuna' => 'Toltén', 'idRegion' => '12', 'idRegionComuna' => '12Toltén'],
            ['comuna' => 'Vilcún', 'idRegion' => '12', 'idRegionComuna' => '12Vilcún'],
            ['comuna' => 'Villarrica', 'idRegion' => '12', 'idRegionComuna' => '12Villarrica'],
            ['comuna' => 'Valdivia', 'idRegion' => '13', 'idRegionComuna' => '13Valdivia'],
            ['comuna' => 'Corral', 'idRegion' => '13', 'idRegionComuna' => '13Corral'],
            ['comuna' => 'Lanco', 'idRegion' => '13', 'idRegionComuna' => '13Lanco'],
            ['comuna' => 'Los Lagos', 'idRegion' => '13', 'idRegionComuna' => '13Los Lagos'],
            ['comuna' => 'Máfil', 'idRegion' => '13', 'idRegionComuna' => '13Máfil'],
            ['comuna' => 'Mariquina', 'idRegion' => '13', 'idRegionComuna' => '13Mariquina'],
            ['comuna' => 'Paillaco', 'idRegion' => '13', 'idRegionComuna' => '13Paillaco'],
            ['comuna' => 'Panguipulli', 'idRegion' => '13', 'idRegionComuna' => '13Panguipulli'],
            ['comuna' => 'La Unión', 'idRegion' => '13', 'idRegionComuna' => '13La'],
            ['comuna' => 'Futrono', 'idRegion' => '13', 'idRegionComuna' => '13Futrono'],
            ['comuna' => 'Lago Ranco', 'idRegion' => '13', 'idRegionComuna' => '13Lago Ranco'],
            ['comuna' => 'Río Bueno', 'idRegion' => '13', 'idRegionComuna' => '13Río Bueno'],
            ['comuna' => 'Osorno', 'idRegion' => '14', 'idRegionComuna' => '14Osorno'],
            ['comuna' => 'Puerto Octay', 'idRegion' => '14', 'idRegionComuna' => '14Puerto Octay'],
            ['comuna' => 'Purranque', 'idRegion' => '14', 'idRegionComuna' => '14Purranque'],
            ['comuna' => 'Puyehue', 'idRegion' => '14', 'idRegionComuna' => '14Puyehue'],
            ['comuna' => 'Río Negro', 'idRegion' => '14', 'idRegionComuna' => '14Río Negro'],
            ['comuna' => 'San Juan de la Costa', 'idRegion' => '14', 'idRegionComuna' => '14San Juan de la Costa'],
            ['comuna' => 'San Pablo', 'idRegion' => '14', 'idRegionComuna' => '14San Pablo'],
            ['comuna' => 'Calbuco', 'idRegion' => '14', 'idRegionComuna' => '14Calbuco'],
            ['comuna' => 'Cochamó', 'idRegion' => '14', 'idRegionComuna' => '14Cochamó'],
            ['comuna' => 'Fresia', 'idRegion' => '14', 'idRegionComuna' => '14Fresia'],
            ['comuna' => 'Frutillar', 'idRegion' => '14', 'idRegionComuna' => '14Frutillar'],
            ['comuna' => 'Llanquihue', 'idRegion' => '14', 'idRegionComuna' => '14Llanquihue'],
            ['comuna' => 'Los Muermos', 'idRegion' => '14', 'idRegionComuna' => '14Los Muermos'],
            ['comuna' => 'Maullín', 'idRegion' => '14', 'idRegionComuna' => '14Maullín'],
            ['comuna' => 'Puerto Montt', 'idRegion' => '14', 'idRegionComuna' => '14Puerto Montt'],
            ['comuna' => 'Puerto Varas', 'idRegion' => '14', 'idRegionComuna' => '14Puerto Varas'],
            ['comuna' => 'Ancud', 'idRegion' => '14', 'idRegionComuna' => '14Ancud'],
            ['comuna' => 'Castro', 'idRegion' => '14', 'idRegionComuna' => '14Castro'],
            ['comuna' => 'Chonchi', 'idRegion' => '14', 'idRegionComuna' => '14Chonchi'],
            ['comuna' => 'Curaco de Vélez', 'idRegion' => '14', 'idRegionComuna' => '14Curaco de Vélez'],
            ['comuna' => 'Dalcahue', 'idRegion' => '14', 'idRegionComuna' => '14Dalcahue'],
            ['comuna' => 'Puqueldón', 'idRegion' => '14', 'idRegionComuna' => '14Puqueldón'],
            ['comuna' => 'Queilén', 'idRegion' => '14', 'idRegionComuna' => '14Queilén'],
            ['comuna' => 'Quellón', 'idRegion' => '14', 'idRegionComuna' => '14Quellón'],
            ['comuna' => 'Quemchi', 'idRegion' => '14', 'idRegionComuna' => '14Quemchi'],
            ['comuna' => 'Quinchao', 'idRegion' => '14', 'idRegionComuna' => '14Quinchao'],
            ['comuna' => 'Chaitén', 'idRegion' => '14', 'idRegionComuna' => '14Chaitén'],
            ['comuna' => 'Futaleufú', 'idRegion' => '14', 'idRegionComuna' => '14Futaleufú'],
            ['comuna' => 'Hualaihué', 'idRegion' => '14', 'idRegionComuna' => '14Hualaihué'],
            ['comuna' => 'Palena', 'idRegion' => '14', 'idRegionComuna' => '14Palena'],
            ['comuna' => 'Lago Verde', 'idRegion' => '15', 'idRegionComuna' => '15Lago Verde'],
            ['comuna' => 'Coihaique', 'idRegion' => '15', 'idRegionComuna' => '15Coihaique'],
            ['comuna' => 'Aysén', 'idRegion' => '15', 'idRegionComuna' => '15Aysén'],
            ['comuna' => 'Cisnes', 'idRegion' => '15', 'idRegionComuna' => '15Cisnes'],
            ['comuna' => 'Guaitecas', 'idRegion' => '15', 'idRegionComuna' => '15Guaitecas'],
            ['comuna' => 'Río Ibáñez', 'idRegion' => '15', 'idRegionComuna' => '15Río Ibáñez'],
            ['comuna' => 'Chile Chico', 'idRegion' => '15', 'idRegionComuna' => '15Chile Chico'],
            ['comuna' => 'Cochrane', 'idRegion' => '15', 'idRegionComuna' => '15Cochrane'],
            ['comuna' => 'O\'Higgins', 'idRegion' => '15', 'idRegionComuna' => '15O\'Higgins'],
            ['comuna' => 'Tortel', 'idRegion' => '15', 'idRegionComuna' => '15Tortel'],
            ['comuna' => 'Natales', 'idRegion' => '16', 'idRegionComuna' => '16Natales'],
            ['comuna' => 'Torres del Paine', 'idRegion' => '16', 'idRegionComuna' => '16Torres del Paine'],
            ['comuna' => 'Laguna Blanca', 'idRegion' => '16', 'idRegionComuna' => '16Laguna Blanca'],
            ['comuna' => 'Punta Arenas', 'idRegion' => '16', 'idRegionComuna' => '16Punta Arenas'],
            ['comuna' => 'Río Verde', 'idRegion' => '16', 'idRegionComuna' => '16Río Verde'],
            ['comuna' => 'San Gregorio', 'idRegion' => '16', 'idRegionComuna' => '16San Gregorio'],
            ['comuna' => 'Porvenir', 'idRegion' => '16', 'idRegionComuna' => '16Porvenir'],
            ['comuna' => 'Primavera', 'idRegion' => '16', 'idRegionComuna' => '16Primavera'],
            ['comuna' => 'Timaukel', 'idRegion' => '16', 'idRegionComuna' => '16Timaukel'],
            ['comuna' => 'Cabo de Hornos', 'idRegion' => '16', 'idRegionComuna' => '16Cabo de Hornos'],
            ['comuna' => 'Antártica', 'idRegion' => '16', 'idRegionComuna' => '16Antártica'],
        ];

        foreach($comunas as $comuna){
            $comuna1 = SYS_comunas::create($comuna);
        };
    }
}
    