<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\SYS_sucursales;

class sucursalesSeeder extends Seeder
{
    public function run()
    {
        $sucursales = [                
            ['codigo' => 'T84', 'centroCosto' => '188', 'bodega' => '84A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'LOC. DOMINICOS', 'idEmpresaMarca' => '1', 'direccion' => 'AV. PADRE HURTADO # 875, LOCAL A-2113/A-2117,LAS CONDES', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '112', 'idUsuario' => '126'],
            ['codigo' => 'T90', 'centroCosto' => '179', 'bodega' => '90A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA NORTE', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA AMERICO VESPUCIO 1737, LOCAL A-1113/A-1117', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '112', 'idUsuario' => '87'],
            ['codigo' => 'T17', 'centroCosto' => '110', 'bodega' => '17A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL MARINA ARAUCO', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA LIBERTAD 1348, 2163', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '6', 'idComuna' => '66', 'idUsuario' => '95'],
            ['codigo' => 'T18', 'centroCosto' => '140', 'bodega' => '18A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL ALTO LAS CONDES', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA PRESIDENTE KENNEDY 9001, 2163', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '105', 'idUsuario' => '89'],
            ['codigo' => 'T75', 'centroCosto' => '193', 'bodega' => '75A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL ARAUCO CHILLAN', 'idEmpresaMarca' => '1', 'direccion' => 'EL ROBLE 770, 222', 'idZona' => '3', 'idPais' => '1', 'idRegion' => '10', 'idComuna' => '199', 'idUsuario' => '90'],
            ['codigo' => 'T56', 'centroCosto' => '155', 'bodega' => '56A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL ARAUCO MAIPÚ', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA AMERICO VESPUCIO 399, 520', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '100', 'idUsuario' => '91'],
            ['codigo' => 'T59', 'centroCosto' => '165', 'bodega' => '59A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL COSTANERA CENTER', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA ANDRES BELLO 2465, 2121', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '96', 'idUsuario' => '92'],
            ['codigo' => 'T64', 'centroCosto' => '190', 'bodega' => '64A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL CONCEPCIÓN CENTRO', 'idEmpresaMarca' => '1', 'direccion' => 'BARROS ARANA 1080, 20', 'idZona' => '3', 'idPais' => '1', 'idRegion' => '11', 'idComuna' => '233', 'idUsuario' => '93'],
            ['codigo' => 'T19', 'centroCosto' => '125', 'bodega' => '19A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL FLORIDA CENTER', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA VICUNA MACKENNA 6100, 2069', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '109', 'idUsuario' => '94'],
            ['codigo' => 'T11', 'centroCosto' => '120', 'bodega' => '11A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PARQUE ARAUCO', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA PRESIDENTE KENNEDY 5413, 329', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '105', 'idUsuario' => '96'],
            ['codigo' => 'T65', 'centroCosto' => '185', 'bodega' => '65A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA ANTOFAGASTA', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA BALMACEDA 2355, 123B-125', 'idZona' => '1', 'idPais' => '1', 'idRegion' => '3', 'idComuna' => '17', 'idUsuario' => '97'],
            ['codigo' => 'T61', 'centroCosto' => '170', 'bodega' => '61A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA DE LOS RIOS', 'idEmpresaMarca' => '1', 'direccion' => 'ARAUCO 561, 159', 'idZona' => '3', 'idPais' => '1', 'idRegion' => '13', 'idComuna' => '284', 'idUsuario' => '98'],
            ['codigo' => 'T68', 'centroCosto' => '196', 'bodega' => '68A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA EGAÑA', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA LARRAIN 5800, B-1024/B-1028', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '106', 'idUsuario' => '99'],
            ['codigo' => 'T71', 'centroCosto' => '194', 'bodega' => '71A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA LA SERENA', 'idEmpresaMarca' => '1', 'direccion' => 'ALBERTO SOLARI 1400, A118 - 120', 'idZona' => '1', 'idPais' => '1', 'idRegion' => '5', 'idComuna' => '30', 'idUsuario' => '100'],
            ['codigo' => 'T55', 'centroCosto' => '150', 'bodega' => '55A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA OESTE', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA AMERICO VESPUCIO 1501, A237-A241', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '117', 'idUsuario' => '101'],
            ['codigo' => 'T67', 'centroCosto' => '195', 'bodega' => '67A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA TOBALABA', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA CAMILO HENRIQUEZ 3296, D136', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '118', 'idUsuario' => '102'],
            ['codigo' => 'T10', 'centroCosto' => '135', 'bodega' => '10A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA TRÉBOL', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA JORGE ALESSANDRI 3177, A-118-120', 'idZona' => '3', 'idPais' => '1', 'idRegion' => '11', 'idComuna' => '243', 'idUsuario' => '103'],
            ['codigo' => 'T34', 'centroCosto' => '115', 'bodega' => '34A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'MALL PLAZA VESPUCIO', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA VICUNA MACKENNA ORIENTE 7110, 251', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '109', 'idUsuario' => '104'],
            ['codigo' => 'T79', 'centroCosto' => '186', 'bodega' => '79A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'OUTLET LA FABRICA', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA ALCALDE CARLOS VALDOVINOS 200, E9', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '90', 'idUsuario' => '105'],
            ['codigo' => 'T70', 'centroCosto' => '198', 'bodega' => '70A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'OUTLET VIÑA PARK', 'idEmpresaMarca' => '1', 'direccion' => 'CAMINO INTERNACIONAL 2404, 04-B', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '6', 'idComuna' => '66', 'idUsuario' => '106'],
            ['codigo' => 'T63', 'centroCosto' => '180', 'bodega' => '63A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'PORTAL OSORNO', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA PLAZA YUNGAY 609, 2012', 'idZona' => '3', 'idPais' => '1', 'idRegion' => '14', 'idComuna' => '296', 'idUsuario' => '107'],
            ['codigo' => 'T60', 'centroCosto' => '175', 'bodega' => '60A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'PORTAL RANCAGUA', 'idEmpresaMarca' => '1', 'direccion' => 'CARRETERA EL COBRE PRESIDENTE FREI MONTALVA 750, 1013', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '8', 'idComuna' => '148', 'idUsuario' => '108'],
            ['codigo' => 'T73', 'centroCosto' => '191', 'bodega' => '73A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'PORTAL TEMUCO', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA ALEMANIA 671, 3002', 'idZona' => '3', 'idPais' => '1', 'idRegion' => '12', 'idComuna' => '263', 'idUsuario' => '109'],
            ['codigo' => 'T69', 'centroCosto' => '197', 'bodega' => '69A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'OUTLET BUENAVENTURA', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA SAN IGNACIO 500, 44', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '94', 'idUsuario' => '110'],
            ['codigo' => 'T82', 'centroCosto' => '187', 'bodega' => '82A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'OUTLET COQUIMBO', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA LA CANTERA 2325, 27-A', 'idZona' => '1', 'idPais' => '1', 'idRegion' => '5', 'idComuna' => '31', 'idUsuario' => '111'],
            ['codigo' => 'T89', 'centroCosto' => '178', 'bodega' => '89A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'PORTAL EL LLANO', 'idEmpresaMarca' => '1', 'direccion' => 'LLANO SUBERCASEAUX 3519, 1099', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '89', 'idUsuario' => '88'],
            ['codigo' => 'T74', 'centroCosto' => '192', 'bodega' => '74A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'OUTLET CURAUMA', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA LOMAS DE LA LUZ 4650, 507', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '6', 'idComuna' => '65', 'idUsuario' => '112'],
            ['codigo' => 'T72', 'centroCosto' => '199', 'bodega' => '72A', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'OUTLET SAN PEDRO', 'idEmpresaMarca' => '1', 'direccion' => 'AVENIDA PORTAL SAN PEDRO 4850, 11', 'idZona' => '3', 'idPais' => '1', 'idRegion' => '11', 'idComuna' => '241', 'idUsuario' => '113'],
            ['codigo' => 'ST1', 'centroCosto' => null, 'bodega' => 'ST1', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'SCALPERS CASA COSTANERA', 'idEmpresaMarca' => '3', 'direccion' => 'AVENIDA PRESIDENTE KENNEDY 9001, 1033', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '96', 'idUsuario' => '115'],
            ['codigo' => 'ST2', 'centroCosto' => null, 'bodega' => 'ST2', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'SCALPERS ALTO LAS CONDES', 'idEmpresaMarca' => '3', 'direccion' => 'AVENIDA ANDRES BELLO 2465, 2153', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '7', 'idComuna' => '105', 'idUsuario' => '114'],
            ['codigo' => 'VD1', 'centroCosto' => '174', 'bodega' => 'CUR', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'VENTA DIRECTA 1', 'idEmpresaMarca' => '2', 'direccion' => 'CERRO EL PROMO 3402, CURAUMA', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '6', 'idComuna' => '122'],
            ['codigo' => 'VD2', 'centroCosto' => '174', 'bodega' => 'CUR', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'VENTA DIRECTA 2', 'idEmpresaMarca' => '2', 'direccion' => 'CERRO EL PROMO 3402, CURAUMA', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '6', 'idComuna' => '120'],
            ['codigo' => 'VD4', 'centroCosto' => '174', 'bodega' => 'CUR', 'estado' => true, 'idTipoSucursal' => '1', 'nombre' => 'VENTA DIRECTA 3', 'idEmpresaMarca' => '2', 'direccion' => 'CERRO EL PROMO 3402, CURAUMA', 'idZona' => '2', 'idPais' => '1', 'idRegion' => '6', 'idComuna' => '121'],
        ];

        foreach($sucursales as $sucursal){
            $sucursal1 = SYS_sucursales::create($sucursal);
        };
    }
}