<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\SYS_supervisores;

class supervisoresSeeder extends Seeder
{
    public function run()
    {
         $supervisores = [
            // DANIELA MUGA
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '1'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '2'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '3'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '4'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '5'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '6'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '7'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '8'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '9'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '10'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '11'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '12'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '13'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '14'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '15'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '16'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '17'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '18'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '19'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '20'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '21'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '22'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '23'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '24'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '25'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '26'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '27'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '28'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '29'],
            ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '30'],

            // ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '31'],
            // ['estado' => true, 'idUsuario' => '15', 'idSucursal' => '32'],
            // FABIAN AGUAYO
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '1'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '2'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '3'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '4'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '5'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '6'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '7'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '8'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '9'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '10'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '11'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '12'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '13'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '14'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '15'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '16'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '17'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '18'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '19'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '20'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '21'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '22'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '23'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '24'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '25'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '26'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '27'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '28'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '29'],
            ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '30'],
            // ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '31'],
            // ['estado' => true, 'idUsuario' => '21', 'idSucursal' => '32'],
            // ARTURO HERRERA
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '1'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '2'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '3'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '4'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '5'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '6'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '7'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '8'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '9'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '10'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '11'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '12'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '13'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '14'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '15'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '16'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '17'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '18'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '19'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '20'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '21'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '22'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '23'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '24'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '25'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '26'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '27'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '28'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '29'],
            // ['estado' => true, 'idUsuario' => '127', 'idSucursal' => '30'],
        ];
        foreach($supervisores as $supervisor){
            $supervisor1 = SYS_supervisores::create($supervisor);
        };
    }
}