<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class usersSeeder extends Seeder
{
    public function run()
    {
        $users = [
            // Usuario de Prueba:
            ['name' => 'Test', 'email' => 'test@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('amphora_test'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // Usuarios Base:
            ['name' => 'Aileen Gostling Urrutia', 'email' => 'agostling@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('agostling186'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Andrea Witto Valenzuela', 'email' => 'awitto@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('awitto414'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Bastian Contreras Wasilkowski', 'email' => 'bcontreras@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('bcontreras912'), 'fofiAsignado' => 100000, 'idTipoUsuario' => 3],
            ['name' => 'Benjamin Dib Puelma', 'email' => 'bdib@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('bdib325'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Blazenko Urrutia Vargas', 'email' => 'burrutia@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('burrutia592'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Camila Ahumada Tapia', 'email' => 'cahumada@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('cahumada78'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Camila Aylin Marín Correa', 'email' => 'cmarin@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('cmarin72'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Catalina Hernández Cornejo', 'email' => 'chernandez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('chernandez669'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Catherine Cifuentes Araneda', 'email' => 'ccifuentes@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ccifuentes455'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Chantal Oberli Moth', 'email' => 'coberli@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('coberli100'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Claudio Olave Alvarez', 'email' => 'colave@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('colave780'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Cristopher Saavedra Zelada', 'email' => 'csaavedra@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('csaavedra402'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Daniela Muga Hernández', 'email' => 'dmuga@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('dmuga248'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Debra Lopez Briceño', 'email' => 'dlopezb@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('dlopezb600'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Despacho Amphora', 'email' => 'despacho@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('despacho691'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Diana Ramirez', 'email' => 'kamcolombia@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('kamcolombia404'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Distribución Amphora', 'email' => 'distribucion@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('distribucion397'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Eduardo Mizon Costa', 'email' => 'emizon@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('emizon521'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Fabian Aguayo Ruiz', 'email' => 'faguayo@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('faguayo47'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Fabián Alejandro Santillana Fuentes', 'email' => 'fsantillana@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('fsantillana933'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Fernanda Camus Bolados', 'email' => 'fcamus@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('fcamus836'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Fernando Valencia Mena', 'email' => 'fvalencia@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('fvalencia68'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Flavio Dib Maluk', 'email' => 'fdib@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('fdib130'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Francisca Acevedo Henriquez', 'email' => 'facevedo@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('facevedo470'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Francisco Alfaro Bravo', 'email' => 'falfaro@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('falfaro926'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Francisco Ortega Ferias', 'email' => 'fortega@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('fortega677'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Geidis Hernandez Hidalgo', 'email' => 'ghernandez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ghernandez846'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Gestion Stock', 'email' => 'gestionstock@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('gestionstock264'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Google Analytics', 'email' => 'ganalytics@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ganalytics901'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Graciela Lillo González', 'email' => 'glillo@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('glillo742'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Guillermo Acosta León', 'email' => 'gacostal@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('gacostal397'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Héctor González Urbina', 'email' => 'hgonzalez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('hgonzalez702'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Informática Interandina', 'email' => 'informatica@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('informatica89'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Isabel Margarita García Abalos', 'email' => 'imgarcia@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('imgarcia358'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Isabel Margarita González Sanzo', 'email' => 'igonzalez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('igonzalez938'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Isidora Guzmán Vega', 'email' => 'iguzman@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('iguzman663'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Javiera Perrier Molinari', 'email' => 'jperrier@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('jperrier388'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Jennifer Millacaris Duran', 'email' => 'jmillacaris@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('jmillacaris192'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Jessica Gallardo Navarro', 'email' => 'jgallardo@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('jgallardo777'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Joaquin Sepulveda Contreras', 'email' => 'jsepulveda@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('jsepulveda179'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Jonathan Seguel Mechsner', 'email' => 'jdseguel@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('jdseguel398'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Keisy Riveros Guerrero', 'email' => 'krivero@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('krivero204'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Kelly Santibáñez Collao', 'email' => 'ksantibanez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ksantibanez19'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Kevin Donoso Jimenez', 'email' => 'kdonoso@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('kdonoso558'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Lilian Hernández Cárdenas', 'email' => 'lhernandez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('lhernandez430'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Logística Inversa', 'email' => 'logisticainversa@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('logisticainversa791'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Luis Marchant Torreblanca', 'email' => 'lmarchant@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('lmarchant512'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Macarena  Bascuñan Galvez', 'email' => 'mbascunan@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mbascunan264'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Magdalena San Martin Moreno', 'email' => 'msanmartin@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('msanmartin240'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Marcela Paz Morgado Madariaga', 'email' => 'mmorgado@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mmorgado367'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Marcos Aballay Valdenegro', 'email' => 'maballay@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('maballay627'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'María Inés Morales Barraza', 'email' => 'mmorales@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mmorales645'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Maria Jose Villar Mardones', 'email' => 'mvillar@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mvillar352'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Mariela Farfán Molina', 'email' => 'mfarfan@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mfarfan684'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Marketing Amphora', 'email' => 'marketing@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('marketing717'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Mercado Pago', 'email' => 'mp_inter@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mp_inter634'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Mercado Pago', 'email' => 'mpinter@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mpinter773'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Mercado Pago Existencias', 'email' => 'mpexistencias@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mpexistencias686'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Mercado Pago Retail', 'email' => 'mpretail@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mpretail914'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Mercado Pago Ziol', 'email' => 'mp_ziolstore@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mp_ziolstore465'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Mercado Pago Ziol', 'email' => 'mp_ziol@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mp_ziol265'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Michelle Tirado Maynou', 'email' => 'mtirado@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mtirado484'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Nancy Ramírez Nuñez', 'email' => 'nramirez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('nramirez77'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Nicole Andrea Moreno Soto', 'email' => 'nmoreno@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('nmoreno318'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Pamela Picasso Steinmetz', 'email' => 'ppicasso@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ppicasso517'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Paola Pastene Pastene', 'email' => 'ppastenep@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ppastenep439'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Paola Andrea Yañez Barra', 'email' => 'pyanez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('pyanez910'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Patricio Bocaz Ahumada', 'email' => 'pbocaz@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('pbocaz490'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Paula Blanco Ondarza', 'email' => 'pblanco@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('pblanco42'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Paula Poblete Chaparro', 'email' => 'ppoblete@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ppoblete586'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Picking Amphora', 'email' => 'picking@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('picking852'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Prevencionista Amphora', 'email' => 'prevencionista@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('prevencionista828'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Raúl Ferrer Calderón', 'email' => 'rferrer@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('rferrer831'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Ricardo Rivera Reyes', 'email' => 'rrivera@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('rrivera378'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Richard Diaz Orellana', 'email' => 'rdiaz@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('rdiaz288'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Roberto Montenegro Roblero', 'email' => 'rmontenegro@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('rmontenegro831'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Rodolfo Medina Bello', 'email' => 'rmedina@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('rmedina620'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Rodrigo Araya Villalobos', 'email' => 'raraya@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('raraya855'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Rodrigo Vallejos Venegas', 'email' => 'rvallejos@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('rvallejos810'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Sebastián Arancibia Moreno', 'email' => 'sarancibia@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('sarancibia322'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Sebastián Jerez Vega', 'email' => 'sjerez@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('sjerez861'), 'fofiAsignado' => 100000, 'idTipoUsuario' => 4],
            ['name' => 'Servicio Al Cliente', 'email' => 'servicioalcliente@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('servicioalcliente903'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Shiraz Farage Salmen', 'email' => 'sfarage@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('sfarage445'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Silvana Beiza Acevedo', 'email' => 'sbeiza@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('sbeiza802'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Soporte Grupo Interandina', 'email' => 'soporte@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('soporte439'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza Norte', 'email' => 'plazanorte@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('plazanorte844'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Portal El Llano', 'email' => 'portalelllano@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('portalelllano87'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Alto Las Condes', 'email' => 'altolascondes@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('altolascondes868'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Arauco Chillán', 'email' => 'araucochillan@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('araucochillan541'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Arauco Maipú', 'email' => 'araucomaipu@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('araucomaipu315'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Costanera Center', 'email' => 'costaneracenter@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('costaneracenter506'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall del Centro Concepción', 'email' => 'centroconcepcion@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('centroconcepcion465'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Florida Center', 'email' => 'floridacenter@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('floridacenter510'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Marina Arauco', 'email' => 'marinaarauco@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('marinaarauco932'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Parque Arauco', 'email' => 'parquearauco@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('parquearauco280'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza Antofagasta', 'email' => 'plazaantofagasta@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('plazaantofagasta214'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza De Los Ríos', 'email' => 'plazadelosrios@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('plazadelosrios849'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza Egaña', 'email' => 'plazaegana@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('plazaegana243'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza La Serena', 'email' => 'mallplazalaserena@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('mallplazalaserena928'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza Oeste', 'email' => 'plazaoeste@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('plazaoeste414'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza Tobalaba', 'email' => 'tobalaba@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('tobalaba286'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza Trébol', 'email' => 'plazadeltrebol@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('plazadeltrebol487'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Mall Plaza Vespucio', 'email' => 'plazavespucio@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('plazavespucio482'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Outlet La Fábrica', 'email' => 'outletlafabrica@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('outletlafabrica57'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Outlet Park Viña', 'email' => 'outletpark@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('outletpark432'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Portal Osorno', 'email' => 'portalosorno@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('portalosorno496'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Portal Rancagua', 'email' => 'portalrancagua@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('portalrancagua409'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Portal Temuco', 'email' => 'portaltemuco@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('portaltemuco912'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Premium Outlet Buenaventura', 'email' => 'outletbuenaventura@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('outletbuenaventura354'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Premium Outlet Coquimbo', 'email' => 'outletcoquimbo@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('outletcoquimbo466'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Premium Outlet Curauma', 'email' => 'outletcurauma@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('outletcurauma780'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Premium Outlet San Pedro', 'email' => 'premiumoutletsanpedro@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('premiumoutletsanpedro705'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // ['name' => 'Tienda Amphora Galeria Cristal', 'email' => 'galeriacristal@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('galeriacristal323'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // ['name' => 'Tienda Amphora Agustinas', 'email' => 'agustinas@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('agustinas221'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // ['name' => 'Tienda Amphora Panoramico', 'email' => 'panoramico@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('panoramico993'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // ['name' => 'Tienda Amphora Barrio Independencia', 'email' => 'barrioindependencia@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('barrioindependencia921'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // ['name' => 'Tienda Amphora Huerfanos', 'email' => 'huerfanos@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('huerfanos213'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // ['name' => 'Tienda Amphora Valdivia', 'email' => 'valdivia@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('valdivia102'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // ['name' => 'Tienda Amphora Ahumada', 'email' => 'ahumada@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ahumada931'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            // ['name' => 'Tienda Amphora Outlet Easton', 'email' => 'outleteaston@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('outleteaston912'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Scalpers Alto Las Condes', 'email' => 'altolascondes@scalpers.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('altolascondes217'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Scalpers Casa Costanera', 'email' => 'casacostanera@scalpers.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('casacostanera818'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Valentina Del Pilar Cornejo Altamirano', 'email' => 'vcornejo@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('vcornejo269'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Yessenia Avila Castro', 'email' => 'yavila@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('yavila256'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Yissela Jorquera Valdivia', 'email' => 'yjorquera@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('yjorquera285'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Yosenedith Pacheco Sifone', 'email' => 'ypacheco@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('ypacheco535'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Aley Gonzalez Forero', 'email' => 'agonzalez@ziolstore.com', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('agonzalez767'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Viviana Agüero Smith', 'email' => 'vaguero@ziolstore.com', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('vaguero757'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Yessenia Avila Castro', 'email' => 'yavila@ziolstore.com', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('yavila513'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Andrés Poblete Bustamante', 'email' => 'apoblete@scalpers.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('apoblete989'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Natalia Nassar Weisz', 'email' => 'nnassar@scalpers.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('nnassar882'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Rafael Poblete Munita', 'email' => 'rpoblete@scalpers.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('rpoblete198'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
            ['name' => 'Tienda Amphora Dominicos', 'email' => 'dominicos@amphora.cl', 'rut' => null, 'idColaborador' => null, 'password' => bcrypt('dominicos274'), 'fofiAsignado' => 100000, 'idTipoUsuario' => null],
        ];

        foreach($users as $user){
            $user1 = User::create($user);
        };
    }
}